version: "3.9"  # optional since v1.27.0

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    # links:
    #   - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    ports:
      - 3000:3000

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  # logstash:
  #   image: docker.elastic.co/logstash/logstash
  #   container_name: logstash
  #   secrets:
  #     - source: logstash.conf
  #       target: /usr/share/logstash/pipeline/logstash.conf
  #     - source: logstash.yml
  #       target: /usr/share/logstash/config/logstash.yml
  #     - source: logstash.keystore
  #       target: /usr/share/logstash/config/logstash.keystore
  #     - source: ca.crt
  #       target: /usr/share/logstash/config/certs/ca/ca.crt
  #   networks: ['stack']
  #   depends_on: ['elasticsearch']
  #   healthcheck:
  #     test: bin/logstash -t
  #     interval: 60s
  #     timeout: 50s
  #     retries: 5

    
volumes:
  elasticsearch-data:
    driver: local

# networks:
#   elastic:
#     driver: bridge